// <auto-generated />
namespace CheckINN.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FullDatabaseSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullDatabaseSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "201712111614234_Full-Database-Schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
